dist: trusty
language: bash
branches:
  only:
  - master

script:
- echo "Logging in as ${DOCKER_USER}"
- docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
- docker build -t traccy .
- docker images
- docker tag traccy $DOCKER_USER/traccy
- docker push $DOCKER_USER/traccy
